version: '3'
services:
  redis:
      container_name: redis
      image: redis:5.0
      ports:
        - "16379:6379"
      command: redis-server --appendonly yes
      environment: 
        REDIS_PASSWORD: "password"
      volumes:
        - ./redis-data:/data
        